#!/usr/bin/env node
// Fixture-based tests. No dependencies: `npm test` / `node test/run.js`.
// Acceptance criterion 7 lives here: corrupt or half-written files must never
// crash the monitor.

const fs = require('fs');
const path = require('path');
const os = require('os');
const titles = require('../lib/titles');
const statusLib = require('../lib/status');
const themes = require('../lib/themes');
const configLib = require('../lib/config');
const { isAlive } = require('../lib/platform/win32');

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'claude-monitor-test-'));
let passed = 0, failed = 0;

function is(name, expected, actual) {
  const ok = JSON.stringify(expected) === JSON.stringify(actual);
  console.log(`${ok ? '  ok  ' : '  FAIL'} ${name}`);
  if (!ok) console.log(`        expected: ${JSON.stringify(expected)}\n        actual  : ${JSON.stringify(actual)}`);
  ok ? passed++ : failed++;
}

function fixture(name, lines) {
  const p = path.join(tmp, name);
  fs.writeFileSync(p, lines.join('\n'), 'utf8');
  return p;
}

const userLine = (text, extra) =>
  JSON.stringify({ type: 'user', message: { role: 'user', content: text }, ...(extra || {}) });
const assistantLine = (content, stop, extra) =>
  JSON.stringify({ type: 'assistant', message: { role: 'assistant', model: 'claude-opus-5', content, stop_reason: stop }, gitBranch: 'main', ...(extra || {}) });
const toolResultLine = (id) =>
  JSON.stringify({ type: 'user', message: { role: 'user', content: [{ type: 'tool_result', tool_use_id: id, content: 'output' }] } });

// ---------------------------------------------------------------- titles
console.log('titles');

is('ai-title wins over the first prompt',
  { title: 'Real Title', source: 'ai-title' },
  titles._fromTranscript(fixture('t1.jsonl', [
    userLine('the first question'),
    JSON.stringify({ type: 'ai-title', aiTitle: 'Real Title', sessionId: 'x' }),
  ])));

is('meta turns are skipped, the first real prompt is used',
  { title: 'the actual first prompt', source: 'first-prompt' },
  titles._fromTranscript(fixture('t2.jsonl', [
    userLine('Caveat: The messages below were generated by the user while running local commands.'),
    userLine('<command-name>/init</command-name>'),
    userLine('something', { isMeta: true }),
    userLine('the actual first prompt'),
  ])));

is('corrupt lines are skipped',
  { title: 'intact', source: 'ai-title' },
  titles._fromTranscript(fixture('t3.jsonl', [
    '{ not valid json', '', 'plain text line',
    JSON.stringify({ type: 'ai-title', aiTitle: 'intact' }),
  ])));

is('a half-written final line does not crash',
  { title: 'first message', source: 'first-prompt' },
  titles._fromTranscript(fixture('t4.jsonl', [
    userLine('first message'),
    '{"type":"assistant","message":{"content":[{"type":"te',
  ])));

is('empty file returns null', null, titles._fromTranscript(fixture('t5.jsonl', [''])));

is('only meta turns returns null', null,
  titles._fromTranscript(fixture('t6.jsonl', [
    userLine('<ide_selection>code</ide_selection>'),
    userLine('[Request interrupted by user]'),
  ])));

is('text is extracted from a content array',
  { title: 'block shaped question', source: 'first-prompt' },
  titles._fromTranscript(fixture('t7.jsonl', [
    JSON.stringify({ type: 'user', message: { content: [{ type: 'text', text: 'block shaped question' }] } }),
  ])));

is('tool_result turns are not titles',
  { title: 'the real question', source: 'first-prompt' },
  titles._fromTranscript(fixture('t8.jsonl', [toolResultLine('a'), userLine('the real question')])));

is('cwd encodes to the project directory (measured, case preserved)',
  'c--Users-dev-user-Documents-VSCode',
  titles.encodePath('c:\\Users\\dev.user\\Documents\\VSCode'));

is('a real hyphen in a folder name survives encoding',
  'c--tmp-e-commerce-app', titles.encodePath('c:/tmp/e-commerce/app'));

// ---------------------------------------------------------------- status
console.log('\nstatus');
const derive = (file) => statusLib.derive(file, { now: Date.now() });

is('tool_use -> running, with the tool name as the action',
  ['running', 'Bash'],
  (() => {
    const r = derive(fixture('s1.jsonl', [
      userLine('do it'),
      assistantLine([{ type: 'tool_use', id: '1', name: 'Bash', input: {} }], 'tool_use'),
    ]));
    return [r.status, r.action];
  })());

is('end_turn -> done (green)', 'done',
  derive(fixture('s2.jsonl', [
    userLine('do it'),
    assistantLine([{ type: 'text', text: 'finished' }], 'end_turn'),
  ])).status);

is('AskUserQuestion -> asking (yellow)', 'asking',
  derive(fixture('s3.jsonl', [
    assistantLine([{ type: 'tool_use', id: '1', name: 'AskUserQuestion', input: {} }], 'tool_use'),
  ])).status);

is('interrupt marker -> interrupted (yellow)', 'interrupted',
  derive(fixture('s4.jsonl', [
    assistantLine([{ type: 'tool_use', id: '1', name: 'Bash', input: {} }], 'tool_use'),
    userLine('[Request interrupted by user for tool use]'),
  ])).status);

is('tool_result -> thinking', 'thinking',
  derive(fixture('s5.jsonl', [
    assistantLine([{ type: 'tool_use', id: '1', name: 'Bash', input: {} }], 'tool_use'),
    toolResultLine('1'),
  ])).status);

is('a fresh permission denial -> asking', 'asking',
  derive(fixture('s6.jsonl', [
    assistantLine([{ type: 'tool_use', id: '1', name: 'Bash', input: {} }], 'tool_use'),
    JSON.stringify({ type: 'user', toolDenialKind: 'permission', message: { content: [{ type: 'tool_result', content: 'denied' }] } }),
    assistantLine([{ type: 'tool_use', id: '2', name: 'Bash', input: {} }], 'tool_use', { toolDenialKind: 'permission' }),
  ])).status);

is('a denial the model already moved past does not stay yellow', 'done',
  derive(fixture('s7.jsonl', [
    assistantLine([{ type: 'tool_use', id: '1', name: 'Bash', input: {} }], 'tool_use', { toolDenialKind: 'permission' }),
    toolResultLine('1'),
    assistantLine([{ type: 'text', text: 'took another route' }], 'end_turn'),
  ])).status);

is('sub-agent turns do not decide the session status', 'done',
  derive(fixture('s8.jsonl', [
    assistantLine([{ type: 'text', text: 'done here' }], 'end_turn'),
    JSON.stringify({ type: 'assistant', isSidechain: true, message: { content: [{ type: 'tool_use', id: '9', name: 'Grep' }], stop_reason: 'tool_use' } }),
  ])).status);

is('a drained queue reports zero (enqueue then dequeue)', 0,
  derive(fixture('s9.jsonl', [
    JSON.stringify({ type: 'queue-operation', operation: 'enqueue', content: 'my next message' }),
    JSON.stringify({ type: 'queue-operation', operation: 'dequeue', content: 'my next message' }),
    assistantLine([{ type: 'text', text: 'ok' }], 'end_turn'),
  ])).queued);

is('a pending typed message is counted, internal ones are not', [1, 2],
  (() => {
    const r = derive(fixture('s10.jsonl', [
      JSON.stringify({ type: 'queue-operation', operation: 'enqueue', content: 'my next message' }),
      JSON.stringify({ type: 'queue-operation', operation: 'enqueue', content: '<task-notification>x</task-notification>' }),
      assistantLine([{ type: 'text', text: 'ok' }], 'end_turn'),
    ]));
    return [r.queued, r.queuedAll];
  })());

is('model and branch come out of the same read', ['claude-opus-5', 'main'],
  (() => {
    const r = derive(fixture('s11.jsonl', [assistantLine([{ type: 'text', text: 'hi' }], 'end_turn')]));
    return [r.model, r.branch];
  })());

is('a long-running tool past idleAfterMs reads as idle', 'idle',
  statusLib.derive(fixture('s12.jsonl', [
    assistantLine([{ type: 'tool_use', id: '1', name: 'Bash', input: {} }], 'tool_use'),
  ]), { idleAfterMs: 1, now: Date.now() + 60000 }).status);

is('missing transcript returns idle without throwing', 'idle', derive(null).status);

// ---------------------------------------------------------------- themes
console.log('\nthemes');
is('four built-in themes exist',
  ['dark', 'light', 'solarized', 'mono'],
  Object.keys(themes.BUILT_IN));

is('every built-in theme defines every required key', [],
  Object.entries(themes.BUILT_IN)
    .filter(([, t]) => themes.REQUIRED_KEYS.some((k) => !(k in t)))
    .map(([name]) => name));

is('done is green and asking is amber in dark',
  [[158, 206, 106], [224, 175, 104]],
  [themes.hexToRgb(themes.BUILT_IN.dark.done), themes.hexToRgb(themes.BUILT_IN.dark.asking)]);

is('mono resolves with no colours', true,
  themes.resolve('mono').colours.done === null);

is('an unknown theme falls back to dark and says so',
  ['dark', 'nope'],
  (() => { const r = themes.resolve('nope'); return [r.name, r.fallbackFrom]; })());

is('hexToRgb rejects garbage', null, themes.hexToRgb('not-a-colour'));

// ---------------------------------------------------------------- config
console.log('\nconfig');
is('window strings parse to ms', [1800000, 14400000, 86400000, 0],
  ['30m', '4h', '1d', 0].map(configLib.parseWindow));

is('a bad window string falls back to 4h', 14400000, configLib.parseWindow('banana'));

is('unknown columns are dropped, title is prepended when absent',
  ['title', 'status', 'time'],
  configLib.sanitise({ columns: ['status', 'nonsense', 'time'] }).columns);

is('title is re-added when the user removes it',
  true, configLib.sanitise({ columns: ['status', 'time'] }).columns.includes('title'));

is('a silly refresh rate falls back to the default', 2000,
  configLib.sanitise({ refreshMs: 10 }).refreshMs);

is('unknown keys are preserved (forward compatible)', 'keep me',
  configLib.sanitise({ somethingNew: 'keep me' }).somethingNew);

// ---------------------------------------------------------------- platform
console.log('\nplatform');
is('own pid is alive', true, isAlive(process.pid));
is('a missing pid is not alive', false, isAlive(999999));
is('garbage input does not throw', false, isAlive(undefined));

// ---------------------------------------------------------------- live dirs
console.log('\nlive directories (must not throw)');
try {
  const state = require('../lib/state');
  const registry = require('../lib/registry');
  is('state.bySession returns a Map', true, state.bySession() instanceof Map);
  is('registry.liveSessions returns an array', true, Array.isArray(registry.liveSessions()));
} catch (e) {
  is('reading the real directories', 'no error', e.message);
}

// ---------------------------------------------------------------- hot reload
// fs.watchFile polls once a second, so this section is asynchronous.
console.log('\nconfig hot reload');
const watchTarget = configLib.FILE;
let original = null;
try { original = fs.readFileSync(watchTarget, 'utf8'); } catch (e) { /* none yet */ }

configLib.ensureFile();
const before = configLib.load().theme;
const flipped = before === 'light' ? 'dark' : 'light';

let fired = null;
const stop = configLib.watch((next) => { fired = next.theme; });

fs.writeFileSync(watchTarget, JSON.stringify({ ...configLib.load(), theme: flipped }, null, 2) + '\n', 'utf8');

setTimeout(() => {
  is(`editing config.json fires the watcher (${before} -> ${flipped})`, flipped, fired);
  stop();
  // Restore the user's own config exactly as it was.
  if (original !== null) fs.writeFileSync(watchTarget, original, 'utf8');
  else fs.writeFileSync(watchTarget, JSON.stringify(configLib.DEFAULTS, null, 2) + '\n', 'utf8');

  console.log(`\n${passed} passed · ${failed} failed · fixtures in ${tmp}`);
  process.exit(failed ? 1 : 0);
}, 2600);
