#!/usr/bin/env node
// Faz 6 — fixture tabanli testler. Harici bagimlilik yok: `node test/run.js`.
// Kabul kriteri 7'nin testi: bozuk/yarim JSONL monitor'u COKERTMEZ.

const fs = require('fs');
const path = require('path');
const os = require('os');
const titles = require('../lib/titles');
const { pidYasiyor } = require('../lib/platform/win32');

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'claudemonitor-test-'));
let gecti = 0, kaldi = 0;

function esit(ad, beklenen, gelen) {
  const ok = JSON.stringify(beklenen) === JSON.stringify(gelen);
  console.log(`${ok ? '  OK  ' : '  FAIL'} ${ad}`);
  if (!ok) console.log(`        beklenen: ${JSON.stringify(beklenen)}\n        gelen   : ${JSON.stringify(gelen)}`);
  ok ? gecti++ : kaldi++;
}

function fixture(ad, satirlar) {
  const p = path.join(tmp, ad);
  fs.writeFileSync(p, satirlar.join('\n'), 'utf8');
  return p;
}

const userSatiri = (metin, ek) => JSON.stringify({ type: 'user', message: { role: 'user', content: metin }, ...(ek || {}) });

console.log('titles._parcalardanBaslik');

// 1. ai-title varsa o kazanir — ilk user mesajindan SONRA gelse bile
esit('ai-title bulunur ve first-prompt\'u ezer',
  { title: 'Gercek Baslik', source: 'ai-title' },
  titles._parcalardanBaslik(fixture('1.jsonl', [
    userSatiri('ilk soru burada'),
    JSON.stringify({ type: 'ai-title', aiTitle: 'Gercek Baslik', sessionId: 'x' }),
  ])));

// 2. ai-title yoksa ilk meta OLMAYAN user mesaji
esit('meta mesajlar atlanir, ilk gercek prompt alinir',
  { title: 'asil ilk prompt', source: 'first-prompt' },
  titles._parcalardanBaslik(fixture('2.jsonl', [
    userSatiri('Caveat: The messages below were generated by the user while running local commands.'),
    userSatiri('<command-name>/init</command-name>'),
    userSatiri('bir sey', { isMeta: true }),
    userSatiri('asil ilk prompt'),
  ])));

// 3. Bozuk satirlar cokertmez, saglam satir bulunur
esit('bozuk JSON satirlari atlanir',
  { title: 'saglam', source: 'ai-title' },
  titles._parcalardanBaslik(fixture('3.jsonl', [
    '{ bu gecerli json degil',
    '',
    'düz metin satiri',
    JSON.stringify({ type: 'ai-title', aiTitle: 'saglam' }),
  ])));

// 4. Yarim yazilmis son satir (JSONL'e o an yaziliyor) cokertmez
esit('yarim son satir cokertmez',
  { title: 'ilk mesaj', source: 'first-prompt' },
  titles._parcalardanBaslik(fixture('4.jsonl', [
    userSatiri('ilk mesaj'),
    '{"type":"assistant","message":{"content":[{"type":"te',
  ])));

// 5. Bos dosya -> null (cagiran fallback'e duser)
esit('bos dosya null doner', null, titles._parcalardanBaslik(fixture('5.jsonl', [''])));

// 6. Yalnizca meta mesaj -> null
esit('yalnizca meta -> null', null,
  titles._parcalardanBaslik(fixture('6.jsonl', [
    userSatiri('<ide_selection>kod</ide_selection>'),
    userSatiri('[Request interrupted by user]'),
  ])));

// 7. content dizisi (blok formatinda mesaj)
esit('content dizisinden metin cikarilir',
  { title: 'blok formatinda soru', source: 'first-prompt' },
  titles._parcalardanBaslik(fixture('7.jsonl', [
    JSON.stringify({ type: 'user', message: { content: [{ type: 'text', text: 'blok formatinda soru' }] } }),
  ])));

// 8. tool_result bloklari baslik olmaz
esit('tool_result bloklu user turn atlanir',
  { title: 'gercek soru', source: 'first-prompt' },
  titles._parcalardanBaslik(fixture('8.jsonl', [
    JSON.stringify({ type: 'user', message: { content: [{ type: 'tool_result', content: 'cikti' }] } }),
    userSatiri('gercek soru'),
  ])));

console.log('\ntitles.encodeYol');
esit('cwd -> encoded dizin (olculdu, buyuk-kucuk harf korunur)',
  'c--Users-dev-user-Documents-VSCode',
  titles.encodeYol('c:\\Users\\dev.user\\Documents\\VSCode'));
esit('klasor adindaki gercek tire korunur',
  'c--tmp-e-commerce-app',
  titles.encodeYol('c:/tmp/e-commerce/app'));

console.log('\nplatform.pidYasiyor');
esit('kendi pid canli', true, pidYasiyor(process.pid));
esit('olmayan pid canli degil', false, pidYasiyor(999999));
esit('gecersiz girdi cokertmez', false, pidYasiyor(undefined));

console.log('\nlib/state ve lib/registry bozuk dosyayla cokmez');
const state = require('../lib/state');
const registry = require('../lib/registry');
try {
  const h = state.durumHaritasi();
  const r = registry.canliOturumlar();
  esit('durumHaritasi Map dondu', true, h instanceof Map);
  esit('canliOturumlar dizi dondu', true, Array.isArray(r));
} catch (e) {
  esit('gercek dizinlerde catisma yok', 'hata yok', e.message);
}

console.log(`\n${gecti} gecti · ${kaldi} kaldi · fixture dizini: ${tmp}`);
process.exit(kaldi ? 1 : 0);
