#!/usr/bin/env node
// Fixture-based tests. No dependencies: `npm test` / `node test/run.js`.
// Acceptance criterion 7 lives here: corrupt or half-written files must never
// crash the monitor.

const fs = require('fs');
const path = require('path');
const os = require('os');
const titles = require('../lib/titles');
const statusLib = require('../lib/status');
const themes = require('../lib/themes');
const configLib = require('../lib/config');
const tasksLib = require('../lib/tasks');
const notify = require('../lib/notify');
const ccboard = require('../lib/ccboard');
const projects = require('../lib/projects');
const text = require('../lib/text');
const { isAlive } = require('../lib/platform/win32');

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'claude-monitor-test-'));
let passed = 0, failed = 0;

function is(name, expected, actual) {
  const ok = JSON.stringify(expected) === JSON.stringify(actual);
  console.log(`${ok ? '  ok  ' : '  FAIL'} ${name}`);
  if (!ok) console.log(`        expected: ${JSON.stringify(expected)}\n        actual  : ${JSON.stringify(actual)}`);
  ok ? passed++ : failed++;
}

function fixture(name, lines) {
  const p = path.join(tmp, name);
  fs.writeFileSync(p, lines.join('\n'), 'utf8');
  return p;
}

const userLine = (text, extra) =>
  JSON.stringify({ type: 'user', message: { role: 'user', content: text }, ...(extra || {}) });
const assistantLine = (content, stop, extra) =>
  JSON.stringify({ type: 'assistant', message: { role: 'assistant', model: 'claude-opus-5', content, stop_reason: stop }, gitBranch: 'main', ...(extra || {}) });
const toolResultLine = (id) =>
  JSON.stringify({ type: 'user', message: { role: 'user', content: [{ type: 'tool_result', tool_use_id: id, content: 'output' }] } });

// ---------------------------------------------------------------- titles
console.log('titles');

is('ai-title wins over the first prompt',
  { title: 'Real Title', source: 'ai-title' },
  titles._fromTranscript(fixture('t1.jsonl', [
    userLine('the first question'),
    JSON.stringify({ type: 'ai-title', aiTitle: 'Real Title', sessionId: 'x' }),
  ])));

is('meta turns are skipped, the first real prompt is used',
  { title: 'the actual first prompt', source: 'first-prompt' },
  titles._fromTranscript(fixture('t2.jsonl', [
    userLine('Caveat: The messages below were generated by the user while running local commands.'),
    userLine('<command-name>/init</command-name>'),
    userLine('something', { isMeta: true }),
    userLine('the actual first prompt'),
  ])));

is('corrupt lines are skipped',
  { title: 'intact', source: 'ai-title' },
  titles._fromTranscript(fixture('t3.jsonl', [
    '{ not valid json', '', 'plain text line',
    JSON.stringify({ type: 'ai-title', aiTitle: 'intact' }),
  ])));

is('a half-written final line does not crash',
  { title: 'first message', source: 'first-prompt' },
  titles._fromTranscript(fixture('t4.jsonl', [
    userLine('first message'),
    '{"type":"assistant","message":{"content":[{"type":"te',
  ])));

is('empty file returns null', null, titles._fromTranscript(fixture('t5.jsonl', [''])));

is('only meta turns returns null', null,
  titles._fromTranscript(fixture('t6.jsonl', [
    userLine('<ide_selection>code</ide_selection>'),
    userLine('[Request interrupted by user]'),
  ])));

is('text is extracted from a content array',
  { title: 'block shaped question', source: 'first-prompt' },
  titles._fromTranscript(fixture('t7.jsonl', [
    JSON.stringify({ type: 'user', message: { content: [{ type: 'text', text: 'block shaped question' }] } }),
  ])));

is('tool_result turns are not titles',
  { title: 'the real question', source: 'first-prompt' },
  titles._fromTranscript(fixture('t8.jsonl', [toolResultLine('a'), userLine('the real question')])));

is('cwd encodes to the project directory (measured, case preserved)',
  'c--Users-dev-user-Documents-workspace',
  titles.encodePath('c:\\Users\\dev.user\\Documents\\workspace'));

is('a real hyphen in a folder name survives encoding',
  'c--tmp-e-commerce-app', titles.encodePath('c:/tmp/e-commerce/app'));

// ---------------------------------------------------------------- status
console.log('\nstatus');
const derive = (file) => statusLib.derive(file, { now: Date.now() });

is('tool_use -> running, with the tool name as the action',
  ['running', 'Bash'],
  (() => {
    const r = derive(fixture('s1.jsonl', [
      userLine('do it'),
      assistantLine([{ type: 'tool_use', id: '1', name: 'Bash', input: {} }], 'tool_use'),
    ]));
    return [r.status, r.action];
  })());

is('end_turn -> done (green)', 'done',
  derive(fixture('s2.jsonl', [
    userLine('do it'),
    assistantLine([{ type: 'text', text: 'finished' }], 'end_turn'),
  ])).status);

is('AskUserQuestion -> asking (yellow)', 'asking',
  derive(fixture('s3.jsonl', [
    assistantLine([{ type: 'tool_use', id: '1', name: 'AskUserQuestion', input: {} }], 'tool_use'),
  ])).status);

is('interrupt marker -> interrupted (yellow)', 'interrupted',
  derive(fixture('s4.jsonl', [
    assistantLine([{ type: 'tool_use', id: '1', name: 'Bash', input: {} }], 'tool_use'),
    userLine('[Request interrupted by user for tool use]'),
  ])).status);

is('tool_result -> thinking', 'thinking',
  derive(fixture('s5.jsonl', [
    assistantLine([{ type: 'tool_use', id: '1', name: 'Bash', input: {} }], 'tool_use'),
    toolResultLine('1'),
  ])).status);

is('a fresh permission denial -> asking', 'asking',
  derive(fixture('s6.jsonl', [
    assistantLine([{ type: 'tool_use', id: '1', name: 'Bash', input: {} }], 'tool_use'),
    JSON.stringify({ type: 'user', toolDenialKind: 'permission', message: { content: [{ type: 'tool_result', content: 'denied' }] } }),
    assistantLine([{ type: 'tool_use', id: '2', name: 'Bash', input: {} }], 'tool_use', { toolDenialKind: 'permission' }),
  ])).status);

is('a denial the model already moved past does not stay yellow', 'done',
  derive(fixture('s7.jsonl', [
    assistantLine([{ type: 'tool_use', id: '1', name: 'Bash', input: {} }], 'tool_use', { toolDenialKind: 'permission' }),
    toolResultLine('1'),
    assistantLine([{ type: 'text', text: 'took another route' }], 'end_turn'),
  ])).status);

is('sub-agent turns do not decide the session status', 'done',
  derive(fixture('s8.jsonl', [
    assistantLine([{ type: 'text', text: 'done here' }], 'end_turn'),
    JSON.stringify({ type: 'assistant', isSidechain: true, message: { content: [{ type: 'tool_use', id: '9', name: 'Grep' }], stop_reason: 'tool_use' } }),
  ])).status);

is('a drained queue reports zero (enqueue then dequeue)', 0,
  derive(fixture('s9.jsonl', [
    JSON.stringify({ type: 'queue-operation', operation: 'enqueue', content: 'my next message' }),
    JSON.stringify({ type: 'queue-operation', operation: 'dequeue', content: 'my next message' }),
    assistantLine([{ type: 'text', text: 'ok' }], 'end_turn'),
  ])).queued);

is('a pending typed message is counted, internal ones are not', [1, 2],
  (() => {
    const r = derive(fixture('s10.jsonl', [
      JSON.stringify({ type: 'queue-operation', operation: 'enqueue', content: 'my next message' }),
      JSON.stringify({ type: 'queue-operation', operation: 'enqueue', content: '<task-notification>x</task-notification>' }),
      assistantLine([{ type: 'text', text: 'ok' }], 'end_turn'),
    ]));
    return [r.queued, r.queuedAll];
  })());

is('model and branch come out of the same read', ['claude-opus-5', 'main'],
  (() => {
    const r = derive(fixture('s11.jsonl', [assistantLine([{ type: 'text', text: 'hi' }], 'end_turn')]));
    return [r.model, r.branch];
  })());

is('a long-running tool past idleAfterMs reads as idle', 'idle',
  statusLib.derive(fixture('s12.jsonl', [
    assistantLine([{ type: 'tool_use', id: '1', name: 'Bash', input: {} }], 'tool_use'),
  ]), { idleAfterMs: 1, now: Date.now() + 60000 }).status);

is('missing transcript returns idle without throwing', 'idle', derive(null).status);

// ---------------------------------------------------------------- context
console.log('\ncontext size');
is('context tokens = input + cache_read + cache_creation', 150000,
  statusLib.derive(fixture('c1.jsonl', [
    JSON.stringify({
      type: 'assistant',
      message: {
        model: 'claude-opus-5', stop_reason: 'end_turn',
        content: [{ type: 'text', text: 'hi' }],
        usage: { input_tokens: 20000, cache_read_input_tokens: 120000, cache_creation_input_tokens: 10000 },
      },
    }),
  ]), { now: Date.now() }).contextTokens);

is('no usage block means no context reading', 0,
  statusLib.derive(fixture('c2.jsonl', [userLine('hello')]), { now: Date.now() }).contextTokens);

// ---------------------------------------------------------------- tasks
console.log('\ntask progress');
function taskDir(name, tasks) {
  const dir = path.join(tmp, name);
  fs.mkdirSync(dir, { recursive: true });
  tasks.forEach((t, i) => fs.writeFileSync(path.join(dir, `${i + 1}.json`), JSON.stringify(t), 'utf8'));
  return dir;
}

is('counts completed, in progress and pending', [4, 2, 1, 1],
  (() => {
    const p = tasksLib.progressIn(taskDir('tasks-a', [
      { id: 1, subject: 'one', status: 'completed' },
      { id: 2, subject: 'two', status: 'completed' },
      { id: 3, subject: 'three', status: 'in_progress', activeForm: 'Doing three' },
      { id: 4, subject: 'four', status: 'pending' },
    ]));
    return [p.total, p.completed, p.inProgress, p.pending];
  })());

is('reports the task in progress', 'Doing three',
  tasksLib.progressIn(path.join(tmp, 'tasks-a')).current);

is('a corrupt task file is skipped, the rest still count', 1,
  (() => {
    const dir = taskDir('tasks-b', [{ id: 1, subject: 'ok', status: 'completed' }]);
    fs.writeFileSync(path.join(dir, '2.json'), '{ broken', 'utf8');
    return tasksLib.progressIn(dir).total;
  })());

is('an empty task directory returns null', null,
  tasksLib.progressIn(path.join(tmp, 'no-such-task-dir')));

// ---------------------------------------------------------------- notify
console.log('\nnotifications');
const outbox = [];
const fakeSend = (title, message, project) => { outbox.push({ title, message, project }); return true; };
const nrow = (id, status) => ({ sessionId: id, status, title: 'T ' + id, project: 'p' });

notify.reset();
is('the first frame never notifies (it only primes)', 0,
  notify.check([nrow('a', 'asking')], true, fakeSend));

notify.reset();
notify.check([nrow('b', 'running')], true, fakeSend);
is('a transition into asking notifies once', 1,
  notify.check([nrow('b', 'asking')], true, fakeSend));

is('staying in the same status does not notify again', 0,
  notify.check([nrow('b', 'asking')], true, fakeSend));

notify.reset();
notify.check([nrow('c', 'running')], false, fakeSend);
is('disabled notifications send nothing', 0,
  notify.check([nrow('c', 'asking')], false, fakeSend));

notify.reset();
notify.check([nrow('d', 'running')], true, fakeSend);
is('interrupted also counts as wanting you', 1,
  notify.check([nrow('d', 'interrupted')], true, fakeSend));

is('the message names the session', true,
  outbox.length > 0 && outbox[outbox.length - 1].message.includes('T d'));

// ---------------------------------------------------------------- ccboard
console.log('\nccboard (optional source)');
is('info() never throws and reports a path', true, typeof ccboard.info().path === 'string');
is('an unknown session has no curated name', '', ccboard.name('no-such-session-id'));
is('an unknown session has no usage', null, ccboard.usage('no-such-session-id'));

// ---------------------------------------------------------------- themes
console.log('\nthemes');
is('at least 15 built-in themes ship', true, Object.keys(themes.BUILT_IN).length >= 15);

is('the cswap palette is the one claude-swap actually uses',
  ['#d7875f', '#87af87', '#d7af5f', '#d75f5f'],
  [themes.BUILT_IN.cswap.running, themes.BUILT_IN.cswap.done,
    themes.BUILT_IN.cswap.asking, themes.BUILT_IN.cswap.interrupted]);

is('cswap-light is a separate theme', true,
  themes.names().includes('cswap-light') &&
  themes.BUILT_IN['cswap-light'].running !== themes.BUILT_IN.cswap.running);

is('every built-in theme defines every required key', [],
  Object.entries(themes.BUILT_IN)
    .filter(([, t]) => themes.REQUIRED_KEYS.some((k) => !(k in t)))
    .map(([name]) => name));

is('done is green and asking is amber in dark',
  [[158, 206, 106], [224, 175, 104]],
  [themes.hexToRgb(themes.BUILT_IN.dark.done), themes.hexToRgb(themes.BUILT_IN.dark.asking)]);

is('mono resolves with no colours', true,
  themes.resolve('mono').colours.done === null);

is('an unknown theme falls back to dark and says so',
  ['dark', 'nope'],
  (() => { const r = themes.resolve('nope'); return [r.name, r.fallbackFrom]; })());

is('hexToRgb rejects garbage', null, themes.hexToRgb('not-a-colour'));

// ---------------------------------------------------------------- config
console.log('\nconfig');
is('window strings parse to ms', [1800000, 14400000, 86400000, 0],
  ['30m', '4h', '1d', 0].map(configLib.parseWindow));

is('a bad window string falls back to 4h', 14400000, configLib.parseWindow('banana'));

is('unknown columns are dropped, title is prepended when absent',
  ['title', 'status', 'time'],
  configLib.sanitise({ columns: ['status', 'nonsense', 'time'] }).columns);

is('title is re-added when the user removes it',
  true, configLib.sanitise({ columns: ['status', 'time'] }).columns.includes('title'));

is('a silly refresh rate falls back to the default', 2000,
  configLib.sanitise({ refreshMs: 10 }).refreshMs);

is('unknown keys are preserved (forward compatible)', 'keep me',
  configLib.sanitise({ somethingNew: 'keep me' }).somethingNew);

is('an unknown groupBy falls back to status', 'status',
  configLib.sanitise({ groupBy: 'sideways' }).groupBy);

is('the old group:false spelling still means no grouping', 'none',
  configLib.sanitise({ group: false }).groupBy);

is('animationMs 0 is kept (it means "hold still")', 0,
  configLib.sanitise({ animationMs: 0 }).animationMs);

is('an absurd animationMs falls back to the default', configLib.DEFAULTS.animationMs,
  configLib.sanitise({ animationMs: 5 }).animationMs);

is('density only accepts compact or comfortable',
  ['compact', 'comfortable'],
  [configLib.sanitise({ density: 'compact' }).density,
    configLib.sanitise({ density: 'wat' }).density]);

is('model, effort and ctx sit next to each other by default',
  ['model', 'effort', 'ctx'],
  configLib.DEFAULTS.columns.slice(
    configLib.DEFAULTS.columns.indexOf('model'),
    configLib.DEFAULTS.columns.indexOf('model') + 3));

// ---------------------------------------------------------------- text
console.log('\ntext layout');
is('a short title stays on one line', ['short one'], text.wrap('short one', 20, 2));

is('a long title breaks on a word boundary',
  ['GlobalProtect VPN site', 'filtering bypass test'],
  text.wrap('Network policy review', 22, 2));

is('the last allowed line is ellipsized', true,
  text.wrap('one two three four five six seven eight nine ten eleven', 12, 2).pop().endsWith('…'));

is('no line ever exceeds the column width', true,
  text.wrap('billing-api invoice reconciliation report draft', 18, 3)
    .every((l) => text.width(l) <= 18));

is('a single unbreakable word is split, not dropped', true,
  text.wrap('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 10, 2)[0].length > 0);

is('titleLines 1 falls back to clipping', 1,
  text.wrap('a fairly long title that will not fit', 12, 1).length);

is('an emoji is two cells, a letter is one', 3, text.width('🔧x'));
is('ANSI escapes are invisible', 3, text.width('\x1b[31mabc\x1b[0m'));

// ---------------------------------------------------------------- ctx ramp
console.log('\ncontext colour ramp');
is('a quiet context stays in the dim colour',
  themes.hexToRgb(themes.BUILT_IN.dark.dim), themes.ramp(themes.BUILT_IN.dark, 0.1));

is('the ramp moves as the context fills', true,
  (() => {
    const at = (r) => JSON.stringify(themes.ramp(themes.BUILT_IN.dark, r));
    return at(0.5) !== at(0.8) && at(0.8) !== at(0.99);
  })());

is('a full context lands on the interrupted colour',
  themes.hexToRgb(themes.BUILT_IN.dark.interrupted), themes.ramp(themes.BUILT_IN.dark, 1));

is('mono has no ramp', null, themes.ramp(themes.BUILT_IN.mono, 0.9));

is('every theme produces a ramp except mono', true,
  Object.entries(themes.BUILT_IN)
    .filter(([name]) => name !== 'mono')
    .every(([, t]) => Array.isArray(themes.ramp(t, 0.8))));

// ---------------------------------------------------------------- projects
console.log('\nproject focus');
const fakeRoot = path.join(tmp, 'workspace');
fs.mkdirSync(path.join(fakeRoot, 'alpha-project'), { recursive: true });
fs.mkdirSync(path.join(fakeRoot, 'beta-tool'), { recursive: true });
fs.mkdirSync(path.join(fakeRoot, 'node_modules'), { recursive: true });
fs.writeFileSync(path.join(fakeRoot, 'CLAUDE.md'),
  '# root\n\n| [`alpha-project/`](alpha-project/CLAUDE.md) | stuff |\n', 'utf8');

is('candidates come from CLAUDE.md plus disk, minus noise',
  ['alpha-project', 'beta-tool'],
  projects.candidatesFor(fakeRoot).candidates.map((c) => c.name).sort());

is('the workspace root is found by walking up to CLAUDE.md', fakeRoot,
  projects.workspaceRoot(path.join(fakeRoot, 'alpha-project')));

is('a path mention outweighs prose', 'beta-tool',
  (() => {
    const f = fixture('f1.jsonl', [
      userLine('I was thinking about alpha-project earlier'),
      assistantLine([{ type: 'tool_use', id: '1', name: 'Read', input: { file_path: 'beta-tool/lib/x.js' } }], 'tool_use'),
      assistantLine([{ type: 'tool_use', id: '2', name: 'Read', input: { file_path: 'beta-tool/lib/y.js' } }], 'tool_use'),
      assistantLine([{ type: 'tool_use', id: '3', name: 'Bash', input: { command: 'cd beta-tool/ && npm test' } }], 'tool_use'),
    ]);
    const r = projects.focusOf('sess-focus-1', fakeRoot, f);
    return r && r.name;
  })());

is('thin evidence produces no tag at all', null,
  projects.focusOf('sess-focus-2', fakeRoot, fixture('f2.jsonl', [userLine('hello there')])));

// ---------------------------------------------------------------- platform
console.log('\nplatform');
is('own pid is alive', true, isAlive(process.pid));
is('a missing pid is not alive', false, isAlive(999999));
is('garbage input does not throw', false, isAlive(undefined));

// ---------------------------------------------------------------- live dirs
console.log('\nlive directories (must not throw)');
try {
  const state = require('../lib/state');
  const registry = require('../lib/registry');
  is('state.bySession returns a Map', true, state.bySession() instanceof Map);
  is('registry.liveSessions returns an array', true, Array.isArray(registry.liveSessions()));
} catch (e) {
  is('reading the real directories', 'no error', e.message);
}

// ---------------------------------------------------------------- hot reload
// fs.watchFile polls once a second, so this section is asynchronous.
console.log('\nconfig hot reload');
const watchTarget = configLib.FILE;
let original = null;
try { original = fs.readFileSync(watchTarget, 'utf8'); } catch (e) { /* none yet */ }

configLib.ensureFile();
const before = configLib.load().theme;
const flipped = before === 'light' ? 'dark' : 'light';

let fired = null;
const stop = configLib.watch((next) => { fired = next.theme; });

fs.writeFileSync(watchTarget, JSON.stringify({ ...configLib.load(), theme: flipped }, null, 2) + '\n', 'utf8');

setTimeout(() => {
  is(`editing config.json fires the watcher (${before} -> ${flipped})`, flipped, fired);
  stop();
  // Restore the user's own config exactly as it was.
  if (original !== null) fs.writeFileSync(watchTarget, original, 'utf8');
  else fs.writeFileSync(watchTarget, JSON.stringify(configLib.DEFAULTS, null, 2) + '\n', 'utf8');

  console.log(`\n${passed} passed · ${failed} failed · fixtures in ${tmp}`);
  process.exit(failed ? 1 : 0);
}, 2600);
