#!/usr/bin/env node
// Put a `cmon` command on your PATH, the way cswap.exe sits in ~/.local/bin.
//
//   node scripts/install-command.js              install as `cmon`
//   node scripts/install-command.js --name=cm    pick another name
//   node scripts/install-command.js --dir=<path> pick another directory
//   node scripts/install-command.js --uninstall  remove it
//
// It writes a tiny .cmd shim (works from cmd, PowerShell and Git Bash) plus a
// POSIX shell script of the same name without the extension, so `cmon` works in
// Git Bash too. Both just exec `node <repo>/monitor.js "$@"`, so pulling new
// commits updates the command with no reinstall.
//
// The default directory is ~/.local/bin because that is already on this
// machine's PATH (cswap.exe lives there). If it is not on yours, the script
// says so and prints the one line that fixes it.

const fs = require('fs');
const path = require('path');
const os = require('os');

const argv = process.argv.slice(2);
const value = (name, fallback) => {
  const hit = argv.find((a) => a.startsWith(`--${name}=`));
  return hit ? hit.slice(name.length + 3) : fallback;
};

const NAME = value('name', 'cmon');
const DIR = path.resolve(value('dir', path.join(os.homedir(), '.local', 'bin')));
const MONITOR = path.resolve(__dirname, '..', 'monitor.js');
const UNINSTALL = argv.includes('--uninstall');

const cmdPath = path.join(DIR, NAME + '.cmd');
const shPath = path.join(DIR, NAME);

// %* forwards every flag: cmon --theme=nord --group=focus
const CMD_BODY = [
  '@echo off',
  'REM Generated by claudeMonitor scripts/install-command.js — safe to delete.',
  `node "${MONITOR}" %*`,
  '',
].join('\r\n');

const SH_BODY = [
  '#!/usr/bin/env sh',
  '# Generated by claudeMonitor scripts/install-command.js — safe to delete.',
  `exec node "${MONITOR}" "$@"`,
  '',
].join('\n');

function onPath() {
  const parts = (process.env.PATH || '').split(path.delimiter).map((p) => {
    try { return fs.realpathSync(p).toLowerCase(); } catch (e) { return p.toLowerCase(); }
  });
  let target = DIR.toLowerCase();
  try { target = fs.realpathSync(DIR).toLowerCase(); } catch (e) { /* not created yet */ }
  return parts.includes(target);
}

if (UNINSTALL) {
  // Files are moved aside, not deleted, so an accidental run costs nothing.
  const stamp = new Date().toISOString().replace(/[:.]/g, '-');
  let moved = 0;
  for (const p of [cmdPath, shPath]) {
    if (!fs.existsSync(p)) continue;
    fs.renameSync(p, `${p}.removed.${stamp}`);
    console.log(`moved aside : ${p} -> ${path.basename(p)}.removed.${stamp}`);
    moved++;
  }
  console.log(moved ? '' : `nothing to remove in ${DIR}`);
  process.exit(0);
}

try {
  fs.mkdirSync(DIR, { recursive: true });
  fs.writeFileSync(cmdPath, CMD_BODY, 'utf8');
  fs.writeFileSync(shPath, SH_BODY, 'utf8');
  try { fs.chmodSync(shPath, 0o755); } catch (e) { /* Windows ignores this */ }
} catch (e) {
  console.error(`FAILED: ${e.message}`);
  process.exit(1);
}

console.log(`installed : ${cmdPath}`);
console.log(`            ${shPath}   (Git Bash)`);
console.log(`runs      : node "${MONITOR}"`);
console.log('');

if (onPath()) {
  console.log(`Ready. Open a new terminal and run:  ${NAME}`);
  console.log(`Flags pass straight through:         ${NAME} --theme=nord --group=focus`);
} else {
  console.log(`${DIR} is NOT on your PATH yet. Add it once, in PowerShell:`);
  console.log('');
  console.log(`  [Environment]::SetEnvironmentVariable('Path', $env:Path + ';${DIR}', 'User')`);
  console.log('');
  console.log('Then open a new terminal.');
}
